version: '3'

services:
  tech-service-app:
    container_name: devguild-tech-service
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - .:/home/app:cached
      - ./package.json:/home/app/package.json:cached
    networks:
      - devguild-tech-service-network

  rabbitmq-tech-service:
    container_name: rabbitmq-tech-service
    image: rabbitmq:3-management
    environment: 
      - RABBITMQ_DEFAULT_VHOST=tech-service
      - RABBITMQ_DEFAULT_PASS=tech-service
      - RABBITMQ_DEFAULT_USER=devguild
    ports: 
      - 5672:5672
      - 15672:15672
    networks:
      - devguild-tech-service-network

  db-tech-service:
    image: postgres:9.4
    container_name: devguild-tech-service-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=devguild
      - POSTGRES_PASSWORD=tech-service
      - POSTGRES_DB=devguild-tech-db
    networks:
      - devguild-tech-service-network

networks:
  devguild-tech-service-network:
    name: default_services_network
